### ISSUE TITLE
Updating ReadModels through WriteModel projection

### ISSUE THREAD

**Issue by drcca** [reimagined/resolve#1054]
Hey folks-

Working through my use case (and looking through docs and the sample code), I noticed that the read models don't actually get updated until a read request is made to the framework. At that point in time, it queries the event store to get all outstanding events (using a highwater mark timestamp?) and sends those to the read projection. When this happens it seems to query the events regardless of aggregateId. 

There a few reasons this is problematic for me and I was wondering if you had any suggestions.

I'm running multiple resolve nodes in a cluster. For a given aggregateId, I'm routing all commands for that aggregateId to a single node. The idea being that you can effectively serialize all requests for that aggregateId that way. Having the read models update when the read request comes in means that I may have multiple nodes querying for all events from the storage adapter regardless of aggregateId. I would then have to figure out how to drop some of those on the floor. I was also under the impression that with CQRS we should be able to scale the read and write parts independently. I'm not sure how this would work with this framework and with the way that the read model is implemented/updated.

I was thinking that it might be possible to completely by pass the read side by updating the read model in the write projection. Do you recommend this? Is there another way to do this that I'm missing?

**Comment by superroma** [comment]
Hi,
Read model is created on demand. Which means it is initialized only upon the first query - it may take minutes or hours to build initially (depending on event store size), but after it is built, it is there and kept up-to-date as new events coming, so query would not spend additional time on fetching events.

To trigger read model creation you need to issue a first query, you can do it in the deploy script.

So to summarize: Read model queries are always instant, once read model is built, it is kept up-to-date from the event bus. 

Now back to your use case.

Read model is meant to be a database with ready answers on all queries, so it consumes pretty much all events, and in the event projection function you can decide which to apply. You cannot currently subscribe a read model to a single aggregate.

I definitely cannot recommend updating read models in the write projection, because you would just bypass all the logic for keeping your read model consistent. 

In the read model projection code you can find out what aggregateId you want to keep on the given node and apply only those events (again, this is done not in the query thread, so does not affect query time). The downside (a minor one) is that each node would receive all events from the event bus.

You can use another feature of reSolve - ViewModels. ViewModels are ephemeral read models and built from the event stream upon the query. View models does not require any storage and require one or several aggregateId to be built. 
So each node would just build read model for the given query on the fly. Since event store has snapshots, it can be as fast as querying the read model database. In this scenario you may want to replicate the event store on each node.

I don't know your requirements, but if you are not twitter or instagram, I don't see why would you need a manual assignment of nodes and aggregates. It is much easier to have identical nodes with shared or replicated event store. Every node could perform any command and answer any query.

_Note about on-demand read models building: it seemed like a good idea at early stages, but currently we have some problems and complcations with it, especially in serverless environment, so we likely to remove this feature in the future versions to make everything simle and straghtforward._
