### ISSUE TITLE
executeCommand is not a function

### ISSUE THREAD

**Issue by Iodine-** [reimagined/resolve#1182]
I am trying to follow along with the docs - but I just keep getting `executeCommand` is not a function from my saga.

I logged out the arguments and indeed `executeCommand` along with `scheduleCommand` are both undefined.  I followed the docs, and checked the advanced user example - and everything looks like it lines up with what I have.  Did I miss something, or is there an issue?

**Comment by IhostVlad** [comment]
Ensure that you are using `sideEffects` object, which is passed into saga handlers in context object, near `store` parameter.  
With destructuring it should look like following: `async sagaEventHandler({ sideEffects: { executeCommand } }, event) => {}`  
Does it work well? We will check documentation, maybe this topic is outdates. Thanks!

**Comment by Iodine-** [comment]
That is indeed the issue! 

The example correctly shows using `executeCommand` from `sideEffects` https://github.com/reimagined/resolve/blob/master/examples/hacker-news/common/sagas/user-confirmation.saga.js#L18

However the docs indicate `executeCommand` and `scheduleCommand` are top level properties.  https://reimagined.github.io/resolve/docs/sagas.

Seems to just be a tab out of date.

So to clarify how the saga works then - when starting the application, it will not invoke sideEffects, is that correct?

**Comment by IhostVlad** [comment]
> That is indeed the issue!

Yes, published documentation is few outdated, and will be fixed with further releases. Anyway you can see actual API in examples or integrational tests, they are updated immediately with publishing new version.

> So to clarify how the saga works then - when starting the application, it will not invoke sideEffects, is that correct?

With default behavior saga begins emitting side effects when event timestamp value is greater than application launch timestamp.   
Under the hood each saga has own property indicating timestamp, after reaching which in rebuilding state, saga should performs side effects instead of skipping them.  
Unfortunately there is no official way to adjust this value for each saga.  For research/educational purposes you can [communicate with local event broker](https://github.com/reimagined/resolve/blob/master/examples/hacker-news/common/api-handlers/event-broker-set-property.js) and manually set [internal property](https://github.com/reimagined/resolve/blob/master/packages/core/resolve-runtime/src/common/sagas/saga-event-handler.js#L14), but it's not recommended since it is private API and can be changed in next versions without any notifications

**Comment by MrCheater** [comment]
Fixed in version 0.21.12
