### ISSUE TITLE
Allow passing objects instead of paths to the app config

### ISSUE THREAD

**Issue by gustavopch** [reimagined/resolve#1361]
**Is your feature request related to a problem? Please describe.**
Currently, the app config must receive the path to the files that export the objects with handlers for aggregates, read models, etc. And we must necessarily have different files for each of those objects because each file must use a default export (reSolve doesn't let you use named exports to access those definitions).

**Describe the solution you'd like**
As the title says, I'd like to be able to directly pass the objects to the app config instead of passing the paths.
- It would allow more flexibility on folder structure and how I prefer my imports and exports (default Vs. named);
- It would allow me to define both commands and aggregations in the same file is I want;
- It would let me benefit from TypeScript module resolution and get static type errors when the import is using an invalid path due to some typo.

**Describe alternatives you've considered**
Not sure if there are alternatives here.

**Additional context**
Here's an example of what I'd like to be able to do:

```js
// config.app.js:
import { ShoppingListAggregate } from './common/aggregates/shopping-list'

export const appConfig = {
  // I'm passing the object defined in the snippet below
  aggregates: [ShoppingListAggregate]
}
```

```js
// common/aggregates/shopping-list/index.js
import { commands } from './commands'
import { projection } from './projection'

export const ShoppingListAggregate = {
  name: 'ShoppingList',
  commands,
  projection,
}
```

```js
// common/aggregates/shopping-list/commands.js
export const commands = [
  // Omitted for brevity...
]
```

```js
// common/aggregates/shopping-list/projection.js
export const projection = [
  // Omitted for brevity...
]
```

**Comment by IhostVlad** [comment]
Hi, @gustavopch! Unfortunately your suggestion is impossible to implement, because it meant to mix compile-time and run-time code. In resolve framework files like `config.app.js` are just manifest describing how for compile your application code.  
Although all application files are written in ECMAScript language, you should not mix compile-time part and run-time part. You suggested to perform import in compiler process, which is pointless, because compiler should build your application from provided files, but should not require any objects in self process.

Several examples can be given to better explanation. When you are using `webpack`, you should specify paths to project files in compile manifest (named `webpack.config.js`) https://webpack.js.org/concepts/#entry , but you should not perform any imports in `webpack.config.js` per se. 
If you are developing C++ project, difference is more obvious - your source code is written in C++ language, and your compile manifest is written, for instance, in Cmake language https://riptutorial.com/cmake/example/22391/-hello-world--with-multiple-source-files. Constructions which you had provided in thus issue are equal to write something like this:
```C++
// CMakeLists.txt
cmake_minimum_required(VERSION 2.4)
project(hello_world)
#import "foo.h"
void foo() {}
#import "foo.cpp"
add_executable(app main.cpp foo.cpp) 
```

**Comment by gustavopch** [comment]
Thanks for the explanation, @IhostVlad. I have not yet read much of reSolve's source code (I intend to do it and possibly be an active contributor), but I think I understand why that is not possible.

What about allowing to specify the name of the export? I have two ideas for the API:

**1. Allow specifying the name of the export after a `#`** (cleaner syntax, but harder to extend in the future):
  ```js
  // config.app.js
  export const appConfig = {
    aggregates: [
      {
        name: 'ShoppingList',
        commands: 'common/aggregates/shopping-list#commands',
        projection: 'common/aggregates/shopping-list#projection'
      }
    ]
  }
  ```

**2. Allow specifying the name of the export within an object** (more verbose syntax, but easier to extend in the future):
```js
// config.app.js
export const appConfig = {
  aggregates: [
    {
      name: 'ShoppingList',
      commands: {
        path: 'common/aggregates/shopping-list',
        export: 'commands'
      },
      projection: {
        path: 'common/aggregates/shopping-list,
        export: 'projection'
      }
    }
  ]
}
```

**Why I'm asking for this**:
  - It would give me the freedom to organize my files exactly as I prefer. If I want to have a single file exporting both commands and projections in the case of an aggregate; or projections, state serializer and state deserializer in the case of a read model, I'd be able to do that.
  - It would let me use named exports which provides a cleaner syntax on TypeScript.

**TypeScript with default export**:
```ts

// Must first declare to be able to add the type annotation
const commands: Commands = {
  // Omitted for brevity...
}

// And then export
export default commands
```

**TypeScript with named export**:
```ts
// Can declare with the type annotation and export at the same time
export const commands: Commands = {
  // Omitted for brevity...
}
```

So what do you think? :smiley:

**Comment by MrCheater** [comment]
It is a great suggestion "Allow specifying the name of the export after a #". We'll consider it in the next releases!
