### ISSUE TITLE
Seriously consider rebasing instead of merging

### ISSUE THREAD

**Issue by gustavopch** [reimagined/resolve#1372]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/10941958/79701296-498bc200-8272-11ea-97a8-6f87af623060.png)
:cold_sweat::cold_sweat::cold_sweat::cold_sweat::cold_sweat::cold_sweat::cold_sweat:

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/10941958/79701308-61fbdc80-8272-11ea-8395-7aa985badbb7.png)
:relieved::relieved::relieved::relieved::relieved::relieved::relieved:

**Describe alternatives you've considered**
None.

**Additional context**
Also, conventional commits enforced by https://github.com/conventional-changelog/commitlint would help so much with the readability of the commits (see: https://github.com/reimagined/resolve/issues/1373).

Edit: I realize that the team may prefer to keep using the merge strategy instead of rebasing for many reasons. Consider this issue a just suggestion besides the "Seriously" in the title :smile:.

**Comment by IhostVlad** [comment]
Hi @gustavopch ! Thank you for your suggestion! 
In the reSolve repository we established a workflow that is quite different from the GitHub flow. Let me go into detail.   
In our team, a developer opens a new feature branch, and performs all the work there. When the work is done, the developer squashes all commits into the dev branch. The information that you can find in a branch’s internal commits can be confusing because it contains a lot of work-in-progress stuff.     
When a feature is done, we merge it into the dev branch with an informative commit message and all the necessary tests. So, we pay attention only to commits in the dev, master and release/hotfix-branches, while feature branches can contain any experimental stuff, spikes and other things that require temporary commits.
