### ISSUE TITLE
ROOT_DIRECTORY has to start with '/'

### ISSUE THREAD

**Issue by VadimKhoroshiltsev** [reimagined/resolve#138]

**Comment by IhostVlad** [comment]
Generally `ROOT_DIRECTORY` should starts with leading slash, because of rules of constructing URL-addresses. When you request any web-site with it root, for example `http://google.com`, really browser adds forced one slash at end of origin (Domain name + port), so root address of *every* web-site is one slash `/`. When using subdirectory configuration by `ROOT_DIRECTORY`, it's meant that variable value will be substitute at beginning of every requested URL-addresses, so root address become `ROOT_DIRECTORY + '/'`. Of course, in this case leading slash should stay.
