### ISSUE TITLE
Why is mongodb adapters discontinued?

### ISSUE THREAD

**Issue by adebisi-fa** [reimagined/resolve#1429]
Hello,

Noticed that the **mongodb** adapters (readModel, snapshot, and eventStore) have been removed from this repo.

Any reason for this, please?

Thanks for the great work you're doing with resolve.  It is awesome!!

Regards, please.

Foluso.

**Comment by IhostVlad** [comment]
Hi @adebisi-fa, thank you for reaching out to us!

The current main goals of the reSolve framework and cloud platform are high load capability and high performance of the event store and read models. In the latest release, we focused on supporting large number of concurrent application users, fast event saving, and so on.

All reSolve adapters, except for MongoDB, are SQL-based and support operations that are especially useful under high loads, including transactions and lightweight mutexes. MongoDB does not provide the necessary functionality, and emulating it within a MongoDB database is slow and costly, so the reSolve team came to a decision to stop their support and drop them from the framework core.

Of course, you can write your own adapters, including a MongoDB event store and read model, but you should be aware that they may not meet high load requirements, which is the reSolve cloud platform’s main focus.

**Comment by adrian-gierakowski** [comment]
@IhostVlad 

would you be able to elaborate on the specific problems you encountered and missing/underperforming features of mongodb? Mongo does support transactions. Do you mean that they are not performing enough? Could you point to specific aspects of the PostgreSQL adapters implementation for which you didn’t find performant equivalents in mongodb? 

I’m asking since I’m interested in using this framework but I also rely heavily on mongodb. Maybe I’d be able to find solutions to the problems you encountered.

Thank you!

**Comment by const314** [comment]
Hello @adrian-gierakowski 

The main reasons for MongoDB adapter removal were the lack of transaction support and the absense of the serverless MongoDB implementation at that time. We decided to focus more on the framework's core features and performance and don't spent much time on maintaing various adapters. 

Since then, things have changed and I beleive that now it is possible to implement MongoDB adapters. However, we don't have such plans in the nearest future, but you can create such an adapter on your own. We highly appreciate this kind of community projects and will definitely mention your adapter in docs in the 3rd party modules list.

The following help topics may be helpful: 
https://reimagined.github.io/resolve/docs/api/event-store-adapter/
https://reimagined.github.io/resolve/docs/api/read-model/connector/
https://reimagined.github.io/resolve/docs/custom-read-model-connectors/

Feel free to ask any questions, we'll be glad to help you.

**Comment by adrian-gierakowski** [comment]
@const314 thanks for your reply. I’ll look it into after Christmas.
