### ISSUE TITLE
Connect resolve to already existing express app

### ISSUE THREAD

**Issue by davidsoderberg** [reimagined/resolve#1440]
Hi I would like to connect resolve to already existing express app is it possible?

**Comment by Lykoi18** [comment]
Hi, @davidsoderberg, thank you for reaching out to us!

You can access resolve via the HTTP API (https://reimagined.github.io/resolve/docs/curl) if you want to use only the local app. However, in this case, you will lose the main feature of resolve - the local application can be deployed to the cloud without changes since we use a custom assembly that allows us to implement such functionality. A better and simpler option is to rewrite your express application on resolve.
