### ISSUE TITLE
Read model data is deleted on variables changes

### ISSUE THREAD

**Issue by timbset** [reimagined/resolve#603]
I have a component wrapped by read model connector. Variables are passed from a parent component. After changing variables using action loaded data is deleted. I expect to see previous state with changed the `loading` field to `true`. I need to show something while data is being fetched. And the `loading` field is enough for me to indentify that current state does not match to current variables.

**Comment by IhostVlad** [comment]
In read-model connectors, there is no explicit data deletion, lifecycle is slightly different. 
Middleware 
continuously watches for connected components and examines, for which combinations of read-model name, resolver name and custom arguments, read-model data had been requested. Then middleware performs automatic data fetching and storing in `redux` store. If requested read-model is reactive, middleware also performs automatic refreshing data in store by incoming pre-calculated state differences.
Components are free to choose which `redux` fields to use in props mapping. So, original issue is not applicable to current lifecycle, since connector is just way for automatic loading actual read-model data into `redux` state, when it requested by one or more existing connected components.
When there is no more pending bindings to some read model data, received by read model name, resolve name and custom arguments combination, middleware deletes it.
So, if some component prefers to continue showing old visual state while new read model data is arriving, it can easily store immediate data into `redux` store and manage it custom way.
