### ISSUE TITLE
Question: what happens to unpublished events?

### ISSUE THREAD

**Issue by rkaw92** [reimagined/resolve#978]
Let's say the following sequence of occurrences takes place:
1. User calls the Event Store's `saveEvent` method
2. The storage adapter persists the event: https://github.com/reimagined/resolve/blob/1fd99f385bc347a1b14fdc9ee1533179ff14fd39/packages/core/resolve-es/src/index.js#L111
3. The bus fails to publish the event

Will the event be in a limbo where it remains unpublished forever?

**Comment by IhostVlad** [comment]
> Will the event be in a limbo where it remains unpublished forever?

@rkaw92, you are right - if bus fails, event will not send into bus. Bus is not involved for guaranteed event delivery, since read-models always check actual event-store content. Bus used for fast event delivery, but is not source of strict serial events stream - event from bus is applied only if read-model has guarantee that it is next event without retransmission and reordering.  
In current `resolve` release bus can be used for event exchange between microservices, but `resolve` application is intend usually to be run locally (for development and debug purposes) or in `resolve cloud`.  
So it does not matter whatever event had been delivered over bus or not - if you turn off bus, application behavior will not change. Maybe it become little slow.

**Comment by rkaw92** [comment]
@IhostVlad What about process controllers (sagas), external integrations and others? Leaving events unpublished forever sounds like a bad idea if there are consumers relying on reliable delivery.

**Comment by IhostVlad** [comment]
> What about process controllers (sagas), external integrations and others?  
Mentioned features are in progress. Now only extremely simplified and limited version of saga is available (see https://github.com/reimagined/resolve/tree/master/examples/with-saga), which does not work in `resolve-cloud` and support process events only in read-time in current process.  
Full implementation of process controllers and gateways (external integrations), compatible with `resolve-cloud` infrastructure, will be available in some future releases. 

> Leaving events unpublished forever sounds like a bad idea if there are consumers relying on reliable delivery.
Currently it's supposed that EventStore, which has guaranteed event saving, is only one source of truth. So consumers should only rely on EventStore.  
In actual `resolve` release, if some applications should share and exchange events, this process should be performed via EventStore. 

Reliable delivery event bus, which works fine in local and cloud environments, will be developed in some future releases.
