### ISSUE TITLE
Potentially incomplete storage adapter API documentation

### ISSUE THREAD

**Issue by rkaw92** [reimagined/resolve#979]
**Describe the bug**

This page:
https://github.com/reimagined/resolve/tree/master/packages/adapters/storage-adapters

describes two mandatory Storage Adapter methods: `saveEvent` and `loadEvents`. However, it seems that the Event Store also requires a third method to be present: `getLatestEvent`, because it is used here:
https://github.com/reimagined/resolve/blob/1fd99f385bc347a1b14fdc9ee1533179ff14fd39/packages/core/resolve-es/src/index.js#L127

**Comment by IhostVlad** [comment]
@rkaw92 Thanks for notice, Readme for these packages will be fixed in next release.  
Also, there is much more mandatory methods for storage adapter, inherited from `resolve-storage-base` package: `init`, `connect` and `dispose`.  
Interface between storage adapter and `resolve-es` can be examined here: https://github.com/reimagined/resolve/blob/master/packages/adapters/storage-adapters/resolve-storage-base/src/create-adapter.js#L20-L37  
And interface between base package and it's descendants, for example, here: https://github.com/reimagined/resolve/blob/master/packages/adapters/storage-adapters/resolve-storage-lite/src/index.js#L15-L20

**Comment by MrCheater** [comment]
Fixed in version 0.20.1
