### ISSUE TITLE
Snapshot is always delayed by 1 event

### ISSUE THREAD

**Issue by rkaw92** [reimagined/resolve#980]
There is currently some weirdness related to snapshot handling in `resolve-command`:
* The snapshot is created when *reading events*, not when persisting (!): https://github.com/reimagined/resolve/blob/b6b2d4553394aa1e7b398fee6afb0718138aee52/packages/core/resolve-command/src/index.js#L69
* Due to the above, the snapshotted state will always be delayed by 1 event until somebody tries to rehydrate the aggregate root

**Comment by IhostVlad** [comment]
@rkaw92 Most likely there is no issue there. Let's see in details how aggregate state is being managed.

If there is no snapshot adapter, aggregate state is not persisted anywhere. When aggregate receives new command, it asks eventstore for all events with current aggregateId and pass them into state reducer one-by-one. When aggregate state is built, it passed into command handler, which performs superficial and domain validation (via state), and emits new event or throws error respectively.

If snapshot adapter is attached, workflow does not changed. But instead of reading all events from eventstore from beginning of the time, some previous state have been persisted in storage. Usually snapshot adapter does not perform storing state after each event applying - instead some batch size is used, by default 100 events.

Take in mind that snapshot is never used as single source to receive aggregate root (state). Snapshot allows to reduce amount of events, which should be retrieved from eventstore. So, in your case, last event will be used to rehydrate the aggregate root anyway.
